import { createOrder } from "zmp-sdk";
import { Option, Product } from "types/product";
import { getConfig } from "./config";
import { Cart, SelectedOptions } from "types/cart";

export function calcFinalPrice(product: Product, options?: SelectedOptions) {
  let finalPrice = product.price;
  if (product.sale) {
    if (product.sale.type === "fixed") {
      finalPrice = product.price - product.sale.amount;
    } else {
      finalPrice = product.price * (1 - product.sale.percent);
    }
  }

  if (options && product.variants) {
    const selectedOptions: Option[] = [];
    for (const variantKey in options) {
      const variant = product.variants.find((v) => v.id === variantKey);
      if (variant) {
        const currentOption = options[variantKey];
        if (typeof currentOption === "string") {
          const selected = variant.options.find((o) => o.id === currentOption);
          if (selected) {
            selectedOptions.push(selected);
          }
        } else {
          const selecteds = variant.options.filter((o) =>
            currentOption.includes(o.id),
          );
          selectedOptions.push(...selecteds);
        }
      }
    }
    finalPrice = selectedOptions.reduce((price, option) => {
      if (option.priceChange) {
        if (option.priceChange.type == "fixed") {
          return price + option.priceChange.amount;
        } else {
          return price + product.price * option.priceChange.percent;
        }
      }
      return price;
    }, finalPrice);
  }
  return finalPrice;
}

export function getDummyImage(filename: string) {
  return `https://stc-zmp.zadn.vn/templates/zaui-coffee/dummy/${filename}`;
}

export function isIdentical(
  option1: SelectedOptions,
  option2: SelectedOptions,
) {
  const option1Keys = Object.keys(option1);
  const option2Keys = Object.keys(option2);

  if (option1Keys.length !== option2Keys.length) {
    return false;
  }

  for (const key of option1Keys) {
    const option1Value = option1[key];
    const option2Value = option2[key];

    const areEqual =
      Array.isArray(option1Value) &&
      Array.isArray(option2Value) &&
      [...option1Value].sort().toString() ===
        [...option2Value].sort().toString();

    if (option1Value !== option2Value && !areEqual) {
      return false;
    }
  }

  return true;
}

const PAYMENT_API_URL =
  import.meta.env.VITE_PAYMENT_API_URL ?? "http://localhost:8080";

export interface PayCODOptions {
  note?: string;
  deliveryAddress?: string;
  storeId?: number;
  description?: string;
}

// Cash-on-delivery checkout via Zalo Mini App's CheckoutSDK custom payment
// method. The order mac is generated by our backend (utils/product.ts never
// sees the app's Private Key) — see server/README.md for the callback flow.
const payCOD = async (cart: Cart, opts: PayCODOptions = {}) => {
  const item = cart.map((cartItem) => ({
    id: String(cartItem.product.id),
    amount: cartItem.quantity * calcFinalPrice(cartItem.product, cartItem.options),
  }));
  const amount = item.reduce((total, i) => total + i.amount, 0);
  const desc =
    opts.description ??
    `Thanh toán cho ${getConfig((config) => config.app.title)}`;

  const res = await fetch(`${PAYMENT_API_URL}/orders`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      item,
      amount,
      desc,
      extradata: {
        note: opts.note,
        deliveryAddress: opts.deliveryAddress,
        storeId: opts.storeId,
      },
    }),
  });
  if (!res.ok) {
    throw new Error(`Failed to create order: ${res.status}`);
  }
  const { mac, extradata, method } = await res.json();

  return createOrder({
    desc,
    item,
    amount,
    method,
    extradata,
    mac,
    success: (data) => {
      console.log("Payment success: ", data);
    },
    fail: (err) => {
      console.log("Payment error: ", err);
    },
  });
};

export default payCOD;
